language: node_js
node_js:
- 6
addons:
  firefox: 49.0.1
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script: npm run dist  
notifications:
  slack:
    secure: CF9m1jVv+0A8/d9nMrNiYB0zRUNy6Fw3PzIKaun3buTLIJEIu+kkVmgoliym7Q90mvZhSryp49gyVNa2pjSXPUhcrCL0CtlXrGQkwa+1CkCmx+uXi3UdsOxYbq3hZeIwU2OYUTGAixEACvD6Up1YkmMzA8oNfKckMOEvPdRu2ZMWsUICIcRikJzaDxt86Bik5fBLUzfNCY3/Y37iUmKqd2DRpibkR6h5p3HCyJ63VgeSQxPs+nSg1IU5XEshR0XEoUD9x6gIp4GW24AC/u9bdwsPW2l3CER1HnuiVhUf/3CK91kjoOjoGnhwfYwzSyXjggRPfXfrF1IFV7mX753swzSTAs2B6JScjOZjmJgYqFsGjqjO7XWqu6wUw2n4djIlCrhWlOSwMNpHH+Zuv+joPjqkZMlR+Nj41gQ80Ws59ySNfRnBMIlskh96cMTvzXPFqHiEhCN9KOMM7EaYK7XoVqYxfot0xvzlbJlZZThyOpl93plgvNStfWSXXi3bhhpl1Isr1rlIdRpc0SKZU6LlgcWQ1SV2Z+XpuqBt35MzFq+7BIg+cI2J7kXHzCUTrl9SiYXIsVdI02HOEVAc/s35YzsJtN6P1E591gmqzTvNS2y6J1f0uIkCuOOHaOuJTAhpXR5iFxz1lv5e6eWwyYCh4GkBU9A6p2cSCWVPKh62LWc=
    on_success: change
    on_failure: always
deploy:
  - provider: releases
    api_key:
      secure: BGCnDLiNvtTq6ZYdcTspCpUKYiBU7xpbDMl54dBv/ujP4CFtqIPEU+TTYM7eO6Oi3v8y4DFlLfBT6TZinDTJrzGvsWVhPlvcKYroMQdNgPwmHPE/zDxAltWTpT/u/TxMX5DbsdHzg7BETCiSU/0CiwMikWb8jPyO16kyJO3POZClTPisv5inOEo2XOzI5uxib9JAZJLe2lOFD5ObM1erodnk4964z8RHxt+Izc1GONj9QayoOQJSWwMC3ed1s8sw/RLmV6OuarXwJjXe5beth2evz60h/4TmRhGcNp++JChT4al6sHEE8L3durJMtmhX7pXFTzkfDB7N1VF1T9m+Y71VxqAeEP92Hgj7ADtkNI72UJz4aeqh4APvMF+Y4GeILwOtoHpKSvXU+zO7gtp+pSPgk8DpRS2nsNad082rPLIsjGZyD92lj3Hs7+v/6NcQMRsQdDkAvbPkBj17itTGMuG37yT79pZCltBC8PkxiSDQnjUW5UMAYAR31QBqnQ1tq65LMKoPpducWyyGek6XUb7A1Zrl480lOv0F7R7mH9jp0D0T014QZZSI7BAVYOHCgeH6t8OlfH8P1694iSeKWR8rCRaPD+z69D58gftW7zMY/lJGlpjZpbdb0rHsgT/AlRQ92Un1VQNoKnnxZ/TJAf8uBpHUcaR5SlKbKco2Zko=
    file: dist/phovea_importer.tar.gz
    on:
      tags: true
      repo: phovea/phovea_importer
  - provider: npm
    email: samuel.gratzl@jku.at
    api_key:
      secure: EqIRx6qYyXVXl0YVBwNS7kAiZFEKYYJCmAw74KasWRfuTDE87eAHS6vYh8PcRVSf6O82ii4BLk0t1u3c5EtkNv9Q6JutHg3661/NhHU4OleaddrdmHIjHuxX4fyLeN8cDgckl+Vh8uRNfdsxma6ASB+lOBpoOrIWmplHOaM1Fi93ciAwLgB4ghUkX5qxBDprDijajPjslK4kPoet+A3CWaZneTAerpAkeTDT+aoB8exZb00dNNetJXg7frfkmVZDhT2IWTZsPIBCdDXsBcUOpR9jlNTiavuSr8AzYpIiIIVyfIK7J6w+evC/GbBraAqcq03RAO31SNt7uWNjcMIk4ZtXbQmGspVT9IJCtfFtv0OYHBMVL4LcLR1O1lE4+lkaBhprDKioMZgyDwzfB3tR0bTcrT/An2HbuCMDAv6wi119Hih8/Y2uNWT7h9o00rhpRnpBbjVBXattEbc6CtkI2gRbqZXmsKBZ6DkQUxJ+bKx8ADvRRO8iL9iWgJDnhELxvCHFvgiew1R4cQjMy3vKQiN4R710VsLTPervyUt9YCparBh9MnndIy/2Vi3yKICIz58m68I76nb4776OaVg+l39jD7N7oLh1ppuwWmKS5/vhC9x/77xgtA+p9DAGjgaYNaZiruTXfZBNWjFGhsyiKy+kHLhsPYhIQ1wQPfYi8fw=
    on:
      tags: true
      repo: phovea/phovea_importer
